services:
  sshx11:
    image: sshx11
    build:
      context: .
      args:
        UNAME: "${uname}"
        UID: "${uid}"
        GID: "${gid}"
    network_mode: host
    user: "${uname}"
    hostname: "${hostname}"
    environment:
      - DISPLAY
    volumes:
      - sshx11_home:/test
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/user/.Xauthority
    entrypoint:
      - xterm
volumes:
 sshx11_home:

